FROM microsoft/aspnetcore-build:2.0 AS build-env
WORKDIR /app

COPY src/Backend/Backend.csproj ./
RUN dotnet restore

COPY src/Backend ./
RUN dotnet publish /app -o out

FROM microsoft/aspnetcore:2.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Backend.dll"]