FROM microsoft/dotnet:2.0-sdk AS build-env
WORKDIR /app

COPY src/Client/Client.csproj ./
RUN dotnet restore

COPY src/Client ./
RUN dotnet publish /app -o out

FROM microsoft/dotnet:2.0-runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Client.dll"]